# Generated by Django 5.1.1 on 2024-12-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_medicine_brand_name_medicine_generic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='common_uses',
        ),
    ]
