# Generated by Django 5.1.1 on 2024-12-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_schedule_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once (one-time use)'), ('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('every_4_hours', 'Every 4 hours'), ('every_8_hours', 'Every 8 hours'), ('weekly', 'Weekly'), ('every_other_day', 'Every Other Day')], default='daily', max_length=50),
        ),
    ]
