# Generated by Django 5.1.1 on 2024-12-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_schedule_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group_id',
        ),
    ]
