# Generated by Django 5.1.1 on 2024-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_schedule_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
