# Generated by Django 5.1.1 on 2024-12-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='jian', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='liu', max_length=100),
        ),
    ]
